### PR TITLE
Feature/add extra datas restrict geocoding

### PR DESCRIPTION
**Pull request by Fredxd**
According with @LordSimal , i have add some features:

- For autocomplete field: 
    - Possibility to add geocoding restriction in field options
    - Save city, zip code and country in location field
- For Lat, Lng fields: 
    - Adding geocoder in order to save city, zip code and country in location field 

If needed feel you free to comment or review this PR

Thanks to @LordSimal

### CODE REVIEW

**Comment by LordSimal** [comment]
What a nice addition 👍 
About the Autocomplete-Adaption: Didn't know this was even possible 😄 
Thank you very much.

**Comment by LordSimal** [comment]
But now I get an error when trying to enter a Lat and Long manually.
The JS Error is: 
```
that.geocodeLatLng is not a function
```

Do I have to add an additional API to my Google Map Key?

**Comment by Fredxd** [comment]
No i have miss a function on file, should be good now ;)

**Comment by LordSimal** [comment]
Indeed that fixed it.
With that lets merge it and create a release.

**Pull request merged**
